### ISSUE TITLE
acceleration_firmware_kv260 build failed 

### ISSUE THREAD

**Issue by surender009** [ros-acceleration/ros2acceleration#1]
In Install page point 5
5. build the workspace and deploy firmware for hardware acceleration
```
**colcon build --merge-install** is failing with below error

[Processing: acceleration_firmware_kv260]
[Processing: acceleration_firmware_kv260]
[Processing: acceleration_firmware_kv260]
--- stderr: acceleration_firmware_kv260
chmod: cannot access '/scratch/krs_ws/install/../acceleration/firmware/kv260/imagebuilder/scripts': No such file or directory
---
Finished <<< acceleration_firmware_kv260 [2min 4s]

Summary: 13 packages finished [2min 5s]
  1 package had stderr output: acceleration_firmware_kv260
```

**Comment by surender009** [comment]
i modified git links to ssh and clone the repos using vcs import src --recursive < krs.repos command, then am able to build

**Comment by vmayoral** [comment]
Thanks. See
https://gitlab.com/xilinxrobotics/docs/-/commit/81f49c8311f97fbb515b52f65f49077a26fe6e64
for the latest changes on that end.

Jasvinder should be aware of this as well. Please use
https://gitlab.com/xilinxrobotics/docs/-/blob/krs-alpha/krs.repos and
report any hurdles.
